spring:
  #Database things
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/db
    username: me
    password: me
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #To show the sql commands use the follow property
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
application:
  jwt:
    secretKey: "secured string using several chars, you should change your secret strategy, but that's for later"
    tokenPrefix: "Bearer "
    tokenExpirationAfterDays: 14
    authoritiesPrefix: "authorities"
    singleAuthorityPrefix: "authority"